[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:backend]
command=node /app/backend/server.js
autostart=true
autorestart=true
priority=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PTP_LOGIN="%(ENV_PTP_LOGIN)s",PTP_SECRET="%(ENV_PTP_SECRET)s",PTP_ENDPOINT="%(ENV_PTP_ENDPOINT)s",PTP_RETURN_URL="%(ENV_PTP_RETURN_URL)s",STRIPE_SECRET_KEY="%(ENV_STRIPE_SECRET_KEY)s"

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
